# Generated by Django 4.2.18 on 2025-01-31 14:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_hi", models.TextField(blank=True, null=True)),
                ("answer_hi", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("question_bn", models.TextField(blank=True, null=True)),
                ("answer_bn", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["-created_at"],
            },
        ),
    ]
